name: 'HTML Preview Action'
on: [pull_request]

jobs:
  html_preview:
    runs-on: ubuntu-latest
    name: HTML Preview
    steps:
      - uses: pavi2410/html-preview-action@master
      - name: Get HTML preview link
        uses: ./
